apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "akash-node.fullname" . }}
  labels:
    app: {{ template "akash-node.name" . }}
    chart: {{ template "akash-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    akash.network/component: akashd
spec:
  selector:
    matchLabels:
      app: {{ template "akash-node.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "akash-node.name" . }}
        release: {{ .Release.Name }}
        akash.network/component: akashd
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh" , "/config/run.sh" ]
          env:
            - name: AKASHD_DATA
              value: /data
          ports:
            - containerPort: {{ .Values.akashd.ports.p2p }}
              name: akashd-p2p
            - containerPort: {{ .Values.akashd.ports.rpc }}
              name: akashd-rpc
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: {{ template "akash-node.fullname" . }}
        - name: data
          PersistentVolumeClaim:
            claimName: {{ template "akash-node.fullname" . }}
