apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akash-provider
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
    - host: akash-provider.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-provider
                port:
                  name: gateway
