bases:
  # - github.com/ovrclk/akash/_docs/kustomize/akash-provider?ref=boz/kustomize
  - ../../../../_docs/kustomize/akash-provider

namespace: akash-services

configMapGenerator:

  ##
  # cosmos-sdk client (config.toml) options
  ##
  - name: akash-client-config
    behavior: merge
    literals:
      # - node=tcp://akashd:26657
      # - chain-id=local

  ##
  # Akash provider service option overrides
  ##
  - name: akash-provider-config
    behavior: merge
    literals:
      - ingress-domain=app.localhost
      # - ingress-static-hosts=false

patchesJson6902:

  ##
  #  Configure gateway host in `gateway-host.yaml`.  Its value
  #  should be the hostname from the on-chain Provider.HostURI
  #  field.
  ##

  - path: gateway-host.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: akash-provider
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: akash-provider
      version: v1

secretGenerator:

  ##
  # Account key material
  ##

  - name: akash-provider-keys
    behavior: replace
    files:
      - cache/key.txt
      - cache/key-pass.txt

