apiVersion: apps/v1
kind: Deployment
metadata:
  name: akash-node
spec:
  selector:
    matchLabels:
      akash.network/component: akash-node
      app: akash-node
  template:
    metadata:
      labels:
        akash.network/component: akash-node
        app: akash-node
    spec:
      containers:
        - name: akash-node
          image: ghcr.io/ovrclk/akash:stable
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" , "/boot/run.sh" ]
          env:

            ##
            # boot config
            ##

            - name: AKASH_BOOT_DATA
              value: /boot-data

            - name: AKASH_BOOT_KEYS
              value: /boot-keys

            ##
            # cosmos-sdk app config (app.toml)
            ##

            - name: AKASH_MINIMUM_GAS_PRICES
              valueFrom:
                configMapKeyRef:
                  name: akash-app-config
                  key: minimum-gas-prices

            - name: AKASH_HALT_HEIGHT
              valueFrom:
                configMapKeyRef:
                  name: akash-app-config
                  key: halt-height

            - name: AKASH_HALT_TIME
              valueFrom:
                configMapKeyRef:
                  name: akash-app-config
                  key: halt-time

            - name: AKASH_INTER_BLOCK_CACHE
              valueFrom:
                configMapKeyRef:
                  name: akash-app-config
                  key: inter-block-cache

            - name: AKASH_PRUNING
              valueFrom:
                configMapKeyRef:
                  name: akash-app-config
                  key: pruning

            ##
            # tendermint node config (config.toml)
            ##

            - name: AKASH_HOME
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: home

            - name: AKASH_MONIKER
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: moniker

            - name: AKASH_FAST_SYNC
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: fast_sync

            - name: AKASH_DB_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: db_backend

            - name: AKASH_DB_DIR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: db_dir

            - name: AKASH_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: log_level

            - name: AKASH_LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: log_format

            - name: AKASH_GENESIS_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: genesis_file

            - name: AKASH_PRIV_VALIDATOR_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: priv_validator_key_file

            - name: AKASH_PRIV_VALIDATOR_STATE_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: priv_validator_state_file

            - name: AKASH_PRIV_VALIDATOR_LADDR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: priv_validator_laddr

            - name: AKASH_NODE_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: node_key_file

            - name: AKASH_ABCI
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: abci

            - name: AKASH_PROF_LADDR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: prof_laddr

            - name: AKASH_FILTER_PEERS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: filter_peers

            - name: AKASH_RPC_LADDR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.laddr

            - name: AKASH_RPC_GRPC_LADDR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.grpc_laddr

            - name: AKASH_RPC_GRPC_MAX_OPEN_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.grpc_max_open_connections

            - name: AKASH_RPC_UNSAFE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.unsafe

            - name: AKASH_RPC_MAX_OPEN_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.max_open_connections

            - name: AKASH_RPC_MAX_SUBSCRIPTION_CLIENTS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.max_subscription_clients

            - name: AKASH_RPC_MAX_SUBSCRIPTIONS_PER_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.max_subscriptions_per_client

            - name: AKASH_RPC_TIMEOUT_BROADCAST_TX_COMMIT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.timeout_broadcast_tx_commit

            - name: AKASH_RPC_MAX_BODY_BYTES
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.max_body_bytes

            - name: AKASH_RPC_MAX_HEADER_BYTES
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.max_header_bytes

            - name: AKASH_RPC_TLS_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.tls_cert_file

            - name: AKASH_RPC_TLS_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: rpc.tls_key_file

            - name: AKASH_P2P_LADDR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.laddr

            - name: AKASH_P2P_EXTERNAL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.external_address

            - name: AKASH_P2P_SEEDS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.seeds

            - name: AKASH_P2P_PERSISTENT_PEERS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.persistent_peers

            - name: AKASH_P2P_UPNP
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.upnp

            - name: AKASH_P2P_ADDR_BOOK_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.addr_book_file

            - name: AKASH_P2P_ADDR_BOOK_STRICT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.addr_book_strict

            - name: AKASH_P2P_MAX_NUM_INBOUND_PEERS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.max_num_inbound_peers

            - name: AKASH_P2P_MAX_NUM_OUTBOUND_PEERS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.max_num_outbound_peers

            - name: AKASH_P2P_UNCONDITIONAL_PEER_IDS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.unconditional_peer_ids

            - name: AKASH_P2P_PERSISTENT_PEERS_MAX_DIAL_PERIOD
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.persistent_peers_max_dial_period

            - name: AKASH_P2P_FLUSH_THROTTLE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.flush_throttle_timeout

            - name: AKASH_P2P_MAX_PACKET_MSG_PAYLOAD_SIZE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.max_packet_msg_payload_size

            - name: AKASH_P2P_SEND_RATE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.send_rate

            - name: AKASH_P2P_RECV_RATE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.recv_rate

            - name: AKASH_P2P_PEX
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.pex

            - name: AKASH_P2P_SEED_MODE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.seed_mode

            - name: AKASH_P2P_PRIVATE_PEER_IDS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.private_peer_ids

            - name: AKASH_P2P_ALLOW_DUPLICATE_IP
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.allow_duplicate_ip

            - name: AKASH_P2P_HANDSHAKE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.handshake_timeout

            - name: AKASH_P2P_DIAL_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: p2p.dial_timeout

            - name: AKASH_MEMPOOL_RECHECK
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: mempool.recheck

            - name: AKASH_MEMPOOL_BROADCAST
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: mempool.broadcast

            - name: AKASH_MEMPOOL_WAL_DIR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: mempool.wal_dir

            - name: AKASH_MEMPOOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: mempool.size

            - name: AKASH_MEMPOOL_MAX_TXS_BYTES
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: mempool.max_txs_bytes

            - name: AKASH_MEMPOOL_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: mempool.cache_size

            - name: AKASH_MEMPOOL_MAX_TX_BYTES
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: mempool.max_tx_bytes

            - name: AKASH_FASTSYNC_VERSION
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: fastsync.version

            - name: AKASH_CONSENSUS_WAL_FILE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.wal_file

            - name: AKASH_CONSENSUS_TIMEOUT_PROPOSE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.timeout_propose

            - name: AKASH_CONSENSUS_TIMEOUT_PROPOSE_DELTA
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.timeout_propose_delta

            - name: AKASH_CONSENSUS_TIMEOUT_PREVOTE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.timeout_prevote

            - name: AKASH_CONSENSUS_TIMEOUT_PREVOTE_DELTA
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.timeout_prevote_delta

            - name: AKASH_CONSENSUS_TIMEOUT_PRECOMMIT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.timeout_precommit

            - name: AKASH_CONSENSUS_TIMEOUT_PRECOMMIT_DELTA
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.timeout_precommit_delta

            - name: AKASH_CONSENSUS_TIMEOUT_COMMIT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.timeout_commit

            - name: AKASH_CONSENSUS_SKIP_TIMEOUT_COMMIT
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.skip_timeout_commit

            - name: AKASH_CONSENSUS_CREATE_EMPTY_BLOCKS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.create_empty_blocks

            - name: AKASH_CONSENSUS_CREATE_EMPTY_BLOCKS_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.create_empty_blocks_interval

            - name: AKASH_CONSENSUS_PEER_GOSSIP_SLEEP_DURATION
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.peer_gossip_sleep_duration

            - name: AKASH_CONSENSUS_PEER_QUERY_MAJ23_SLEEP_DURATION
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: consensus.peer_query_maj23_sleep_duration

            - name: AKASH_TX_INDEX_INDEXER
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: tx_index.indexer

            - name: AKASH_TX_INDEX_INDEX_KEYS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: tx_index.index_keys

            - name: AKASH_TX_INDEX_INDEX_ALL_KEYS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: tx_index.index_all_keys

            - name: AKASH_INSTRUMENTATION_PROMETHEUS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: instrumentation.prometheus

            - name: AKASH_INSTRUMENTATION_PROMETHEUS_LISTEN_ADDR
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: instrumentation.prometheus_listen_addr

            - name: AKASH_INSTRUMENTATION_MAX_OPEN_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: instrumentation.max_open_connections

            - name: AKASH_INSTRUMENTATION_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: akash-config
                  key: instrumentation.namespace

          ports:
            - name: akash-rpc
              containerPort: 26657
            - name: akash-p2p
              containerPort: 26656
          volumeMounts:
            - name: boot
              mountPath: /boot
              readOnly: true
            - name: data
              mountPath: /boot-data
              readOnly: true
            - name: keys
              mountPath: /boot-keys
              readOnly: true
      volumes:
        - name: boot
          configMap:
            name: akash-boot
        - name: data
          configMap:
            name: akash-data
        - name: keys
          secret:
            secretName: akash-keys
