resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app: akash-node
  akash.network/component: akash-node

namespace: akash-services

configMapGenerator:

  - name: akash-boot
    files:
      - run.sh

  ##
  # cosmos-sdk app config (app.toml)
  ##
  - name: akash-app-config
    literals:
      - minimum-gas-prices=
      - halt-height=0
      - halt-time=0
      - inter-block-cache=true
      - pruning=nothing

  ##
  # tendermint node config (config.toml)
  ##
  - name: akash-config
    literals:
      - home=/home
      - moniker=node0
      - fast_sync=true
      - db_backend=goleveldb
      - db_dir=data
      - log_level=info
      - log_format=plain

      # configmap: akash-data
      # XXX: not being read
      - genesis_file=/boot-data/genesis.json

      # secret: akash-keys
      # XXX: not being read
      - priv_validator_key_file=/boot-keys/priv_validator_key.json

      # secret: akash-keys
      # XXX: not being read
      - priv_validator_state_file=data/priv_validator_state.json
      - priv_validator_laddr=

      # secret: akash-keys
      # XXX: not being read
      - node_key_file=/boot-keys/node_key.json
      - abci=socket
      - prof_laddr=localhost:6060
      - filter_peers=false

      # rpc
      - rpc.laddr=tcp://0.0.0.0:26657
      - rpc.grpc_laddr=
      - rpc.grpc_max_open_connections=900
      - rpc.unsafe=false
      - rpc.max_open_connections=900
      - rpc.max_subscription_clients=100
      - rpc.max_subscriptions_per_client=5
      - rpc.timeout_broadcast_tx_commit=10s
      - rpc.max_body_bytes=1000000
      - rpc.max_header_bytes=1048576
      - rpc.tls_cert_file=
      - rpc.tls_key_file=

      ##
      # p2p
      ##

      - p2p.laddr=tcp://0.0.0.0:26656
      - p2p.external_address=
      - p2p.seeds=
      - p2p.persistent_peers=
      - p2p.upnp=false
      - p2p.addr_book_file=config/addrbook.json
      - p2p.addr_book_strict=true
      - p2p.max_num_inbound_peers=40
      - p2p.max_num_outbound_peers=10
      - p2p.unconditional_peer_ids=
      - p2p.persistent_peers_max_dial_period=0s
      - p2p.flush_throttle_timeout=100ms
      - p2p.max_packet_msg_payload_size=1024
      - p2p.send_rate=5120000
      - p2p.recv_rate=5120000
      - p2p.pex=true
      - p2p.seed_mode=false
      - p2p.private_peer_ids=
      - p2p.allow_duplicate_ip=false
      - p2p.handshake_timeout=20s
      - p2p.dial_timeout=3s

      ##
      # mempool
      ##

      - mempool.recheck=true
      - mempool.broadcast=true
      - mempool.wal_dir=
      - mempool.size=5000
      - mempool.max_txs_bytes=1073741824
      - mempool.cache_size=10000
      - mempool.max_tx_bytes=1048576

      ##
      # fastsync
      ##

      - fastsync.version=v0

      ##
      # consensus
      ##

      - consensus.wal_file=data/cs.wal/wal
      - consensus.timeout_propose=3s
      - consensus.timeout_propose_delta=500ms
      - consensus.timeout_prevote=1s
      - consensus.timeout_prevote_delta=500ms
      - consensus.timeout_precommit=1s
      - consensus.timeout_precommit_delta=500ms
      - consensus.timeout_commit=5s
      - consensus.skip_timeout_commit=false
      - consensus.create_empty_blocks=true
      - consensus.create_empty_blocks_interval=0s
      - consensus.peer_gossip_sleep_duration=100ms
      - consensus.peer_query_maj23_sleep_duration=2s

      ##
      # tx_index
      ##

      - tx_index.indexer=kv
      - tx_index.index_keys=
      - tx_index.index_all_keys=true

      ##
      # instrumentation
      ##

      - instrumentation.prometheus=false
      - instrumentation.prometheus_listen_addr=:26660
      - instrumentation.max_open_connections=3
      - instrumentation.namespace=tendermint

  - name: akash-data
    ##
    #  required files
    ##
    files:
      # - config/genesis.json

secretGenerator:
  - name: akash-keys
    ##
    #  required files
    ##
    files:
      # - config/node_key.json
      # - config/priv_validator_key.json
      # - data/priv_validator_state.json
